apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: auth-db
data:
  POSTGRES_DB: authdb
  POSTGRES_USER: vishal
  POSTGRES_PASSWORD: vishal123
  create_table.sql: |
    CREATE TABLE auth_user (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    email VARCHAR (255) NOT NULL,
    password VARCHAR (255) NOT NULL);
    INSERT INTO auth_user (email, password) VALUES ('thomasfookins007helby@gmail.com', '123456');
    INSERT INTO auth_user (email, password) VALUES ('iambatmanthegoat@gmail.com', '123456');
     


