apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  type: LoadBalancer # Change service type to LoadBalancer
  ports:
  - port: 5000 # External port for the service
    targetPort: 5000 # Internal port where the application is running
    nodePort: 30008 # Port on the node
    protocol: TCP
