apiVersion: v1
kind: Secret
metadata:
  name: notification-secret
stringData:
  GMAIL_ADDRESS: "vikikartoos1997@gmail.com" #enter your email to get the id
  GMAIL_PASSWORD: "zhdu yuim zbxn dssn"
type: Opaque
